from __future__ import annotations

import json
import re
from pathlib import Path

from .models import EndpointCatalog


_PATH_PARAM_RE = re.compile(r"\{(\w+)\}")


def _python_method_name(name: str) -> str:
    return name.replace("-", "_")


def _extract_path_params(url_template: str) -> list[str]:
    # Return unique path param names with index suffixes to avoid duplicates
    seen: dict[str, int] = {}
    params = []
    for match in _PATH_PARAM_RE.finditer(url_template):
        key = match.group(1)
        count = seen.get(key, 0)
        seen[key] = count + 1
        unique_name = f"{key}_{count}" if count > 0 else key
        params.append(unique_name)
    return params


def _format_url(url_template: str, path_params: list[str]) -> str:
    # Build keyword args for .format() from unique param names
    seen: dict[str, int] = {}
    format_args = []
    for match in _PATH_PARAM_RE.finditer(url_template):
        key = match.group(1)
        count = seen.get(key, 0)
        seen[key] = count + 1
        unique_name = f"{key}_{count}" if count > 0 else key
        format_args.append(f"{unique_name}={unique_name}")
    return url_template + ".format(" + ", ".join(format_args) + ")"


def render_python_client(catalog: EndpointCatalog, *, class_name: str = "BrowserClawClient") -> str:
    methods: list[str] = []
    for endpoint in catalog.endpoints:
        path_param_names = _extract_path_params(endpoint.url_template)
        query_arg_names = [key.replace("-", "_") for key in endpoint.query_keys]
        body_arg_names = [key.replace("-", "_") for key in endpoint.request_body_keys]
        seen: set[str] = set()
        all_arg_names = [name for name in query_arg_names + body_arg_names if name not in seen and not seen.add(name)]
        # Path params are positional, query/body params are keyword-only with defaults
        positional_args = ["self", *path_param_names]
        keyword_args = [f"{name}=None" for name in all_arg_names] if all_arg_names else []
        method_args = positional_args + (["*"] + keyword_args if keyword_args else [])
        method_name = _python_method_name(endpoint.name)
        query_payload = ", ".join([f'"{key}": {key.replace("-", "_")}' for key in endpoint.query_keys]) or ""
        json_payload = ", ".join([f'"{key}": {key.replace("-", "_")}' for key in endpoint.request_body_keys]) or ""
        url_for_format = _format_url(endpoint.url_template, path_param_names)
        methods.append(
            f"""    def {method_name}({", ".join(method_args)}):\n"""
            f"""        \"\"\"{endpoint.description}\"\"\"\n"""
            f"""        url = "{url_for_format}"\n"""
            f"""        params = {{{query_payload}}}\n"""
            f"""        params = {{key: value for key, value in params.items() if value is not None}}\n"""
            f"""        payload = {{{json_payload}}}\n"""
            f"""        payload = {{key: value for key, value in payload.items() if value is not None}}\n"""
            f"""        response = self.session.request(\n"""
            f"""            "{endpoint.method}",\n"""
            f"""            url,\n"""
            f"""            params=params or None,\n"""
            f"""            json=payload or None,\n"""
            f"""        )\n"""
            f"""        response.raise_for_status()\n"""
            f"""        return response.json() if response.content else None\n"""
        )

    methods_body = "\n\n".join(methods)
    return f'''"""Generated by browserclaw from {catalog.source_har}."""\n\nimport requests\n\n\nclass {class_name}:\n    def __init__(self, session: requests.Session | None = None):\n        self.session = session or requests.Session()\n\n{methods_body}\n'''


def render_mcp_tools(catalog: EndpointCatalog) -> dict:
    tools = []
    for endpoint in catalog.endpoints:
        properties = {}
        required = []
        for key in endpoint.query_keys + endpoint.request_body_keys:
            safe_name = key.replace("-", "_")
            properties[safe_name] = {
                "type": "string",
                "description": f"Inferred parameter for {key}",
            }
            required.append(safe_name)
        tools.append(
            {
                "name": endpoint.name,
                "description": endpoint.description or f"{endpoint.method} {endpoint.url_template}",
                "inputSchema": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                    "additionalProperties": False,
                },
                "annotations": {
                    "method": endpoint.method,
                    "urlTemplate": endpoint.url_template,
                },
            }
        )
    return {
        "schema_version": "2025-03-26",
        "site": catalog.site,
        "tools": tools,
    }


def generate_bundle(catalog: EndpointCatalog, output_dir: str | Path) -> dict[str, Path]:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    catalog_path = output / "catalog.json"
    client_path = output / "generated_client.py"
    mcp_path = output / "mcp_tools.json"
    catalog_path.write_text(json.dumps(catalog.to_dict(), indent=2) + "\n")
    client_path.write_text(render_python_client(catalog))
    mcp_path.write_text(json.dumps(render_mcp_tools(catalog), indent=2) + "\n")
    return {
        "catalog": catalog_path,
        "client": client_path,
        "mcp": mcp_path,
    }

