from __future__ import annotations

import json
import re
from pathlib import Path

from .models import EndpointCatalog


_PATH_PARAM_RE = re.compile(r"\{(\w+)\}")


def _python_method_name(name: str) -> str:
    return name.replace("-", "_")


def _extract_path_params(url_template: str) -> list[str]:
    # Return unique path param names with index suffixes to avoid duplicates.
    # Use positional args in .format() so duplicate placeholders fill in order.
    seen: dict[str, int] = {}
    params = []
    for match in _PATH_PARAM_RE.finditer(url_template):
        key = match.group(1)
        count = seen.get(key, 0)
        seen[key] = count + 1
        # Rename "self" to avoid conflicting with Python's self parameter
        base = "path_self" if key == "self" else key
        unique_name = f"{base}_{count}" if count > 0 else base
        params.append(unique_name)
    return params


def _format_url(url_template: str, path_params: list[str]) -> str:
    # Use positional args so duplicate {id} placeholders fill in left-to-right order
    return f'"{url_template}".format(' + ", ".join(path_params) + ")"


def render_python_client(catalog: EndpointCatalog, *, class_name: str = "BrowserClawClient") -> str:
    methods: list[str] = []
    for endpoint in catalog.endpoints:
        path_param_names = _extract_path_params(endpoint.url_template)
        query_arg_names = [key.replace("-", "_") for key in endpoint.query_keys]
        body_arg_names = [key.replace("-", "_") for key in endpoint.request_body_keys]
        # Deduplicate query/body args, excluding any that collide with path params
        path_set = set(path_param_names)
        seen: set[str] = set()
        all_arg_names = [
            name for name in query_arg_names + body_arg_names
            if name not in path_set and name not in seen and not seen.add(name)
        ]
        # Path params are positional, query/body params are keyword-only with defaults
        positional_args = ["self", *path_param_names]
        keyword_args = [f"{name}=None" for name in all_arg_names] if all_arg_names else []
        method_args = positional_args + (["*"] + keyword_args if keyword_args else [])
        method_name = _python_method_name(endpoint.name)
        query_payload = ", ".join([f'"{key}": {key.replace("-", "_")}' for key in endpoint.query_keys]) or ""
        json_payload = ", ".join([f'"{key}": {key.replace("-", "_")}' for key in endpoint.request_body_keys]) or ""
        url_for_format = _format_url(endpoint.url_template, path_param_names)
        methods.append(
            f"""    def {method_name}({", ".join(method_args)}):\n"""
            f"""        \"\"\"{endpoint.description}\"\"\"\n"""
            f"""        url = {url_for_format}\n"""
            f"""        params = {{{query_payload}}}\n"""
            f"""        params = {{key: value for key, value in params.items() if value is not None}}\n"""
            f"""        payload = {{{json_payload}}}\n"""
            f"""        payload = {{key: value for key, value in payload.items() if value is not None}}\n"""
            f"""        response = self.session.request(\n"""
            f"""            "{endpoint.method}",\n"""
            f"""            url,\n"""
            f"""            params=params or None,\n"""
            f"""            json=payload or None,\n"""
            f"""        )\n"""
            f"""        response.raise_for_status()\n"""
            f"""        return response.json() if response.content else None\n"""
        )

    methods_body = "\n\n".join(methods)
    return f'''"""Generated by browserclaw from {catalog.source_har}."""\n\nimport requests\n\n\nclass {class_name}:\n    def __init__(self, session: requests.Session | None = None):\n        self.session = session or requests.Session()\n\n{methods_body}\n'''


def render_mcp_tools(catalog: EndpointCatalog) -> dict:
    tools = []
    for endpoint in catalog.endpoints:
        properties = {}
        required = []
        for key in endpoint.query_keys + endpoint.request_body_keys:
            safe_name = key.replace("-", "_")
            properties[safe_name] = {
                "type": "string",
                "description": f"Inferred parameter for {key}",
            }
            required.append(safe_name)
        tools.append(
            {
                "name": endpoint.name,
                "description": endpoint.description or f"{endpoint.method} {endpoint.url_template}",
                "inputSchema": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                    "additionalProperties": False,
                },
                "annotations": {
                    "method": endpoint.method,
                    "urlTemplate": endpoint.url_template,
                },
            }
        )
    return {
        "schema_version": "2025-03-26",
        "site": catalog.site,
        "tools": tools,
    }


def generate_bundle(catalog: EndpointCatalog, output_dir: str | Path) -> dict[str, Path]:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    catalog_path = output / "catalog.json"
    client_path = output / "generated_client.py"
    mcp_path = output / "mcp_tools.json"
    catalog_path.write_text(json.dumps(catalog.to_dict(), indent=2) + "\n")
    client_path.write_text(render_python_client(catalog))
    mcp_path.write_text(json.dumps(render_mcp_tools(catalog), indent=2) + "\n")
    return {
        "catalog": catalog_path,
        "client": client_path,
        "mcp": mcp_path,
    }


# ─── WebSocket Replay Generation ──────────────────────────────────────────────


def render_ws_replay(ws_capture_path: str | Path) -> str:
    """Generate a bash script with websocat commands to replay captured WebSocket frames.

    Also includes Firebase Firestore RPC calls parsed from the WebSocket messages.

    Requires:  pip install websocat
    Or:        brew install websocat
    """
    import json
    from pathlib import Path

    data = json.loads(Path(ws_capture_path).read_text())
    connections = data.get("connections", [])
    fs_calls = data.get("firestore_calls", [])

    lines = [
        "#!/usr/bin/env bash",
        "# WebSocket replay script — generated by browserclaw",
        "#",
        "# Prerequisites:",
        "#   pip install websocat    # or: brew install websocat",
        "#   websocat -h             # verify installation",
        "#",
        "# Usage: bash /path/to/replay.sh",
        "#",
        "# NOTE: Firestore WebSocket connections require valid Firebase auth.",
        "#       Replay may fail if the stream token has expired.",
        "#",
        "",
        "set -e",
        "",
    ]

    # ── Firestore calls ────────────────────────────────────────────────────────
    firestore_conns = [c for c in connections if c.get("is_firestore")]
    if firestore_conns:
        lines += [
            "###############################################################################",
            "# FIREBASE FIRESTORE WEBSOCKET CONNECTIONS",
            f"# Found {len(firestore_conns)} Firestore WS connection(s)",
            "###############################################################################",
            "",
        ]
        for idx, conn in enumerate(firestore_conns):
            ws_url = conn["url"]
            # Truncate long Firestore URLs for readability
            if len(ws_url) > 100:
                ws_url_display = ws_url[:100] + "..."
            else:
                ws_url_display = ws_url
            lines += [
                f"# Connection {idx + 1}: {ws_url_display}",
                f"#   Frames: {conn['frame_count']}",
                "",
            ]
        lines += [
            "#",
            "# ── Example websocat replay for Firestore WS ──",
            "#",
            "# websocat -n1 'WSS://firestore.googleapis.com/google.firestore.v1.WEBSOCKET_ENDPOINT' \\",
            "#   --header 'Authorization: Bearer <YOUR_FIREBASE_TOKEN>' \\",
            "#   --header 'X-Goog-Api-Key: <API_KEY>' \\",
            "#   --header 'X-Goog-AuthUser: 0' \\",
            "#   -v 2>&1 | head -50",
            "#",
        ]

    # ── Generic WebSocket connections ──────────────────────────────────────────
    generic_conns = [c for c in connections if not c.get("is_firestore")]
    if generic_conns:
        lines += [
            "",
            "###############################################################################",
            "# GENERIC WEBSOCKET CONNECTIONS",
            f"# Found {len(generic_conns)} non-Firestore WS connection(s)",
            "###############################################################################",
            "",
        ]
        for idx, conn in enumerate(generic_conns):
            ws_url = conn["url"]
            lines += [
                f"# ── WS Connection {idx + 1} ──",
                f"# URL: {ws_url}",
                f"# Frames: {conn['frame_count']} | Created: {conn.get('created_at', 'N/A')}",
                f"#",
                f"# Replay:",
                f"websocat -n1 '{ws_url}' \\",
                f"  -v 2>&1 | head -100",
                "",
            ]

    # ── Firestore RPC calls ────────────────────────────────────────────────────
    if fs_calls:
        lines += [
            "",
            "###############################################################################",
            "# FIRESTORE RPC CALLS (parsed from WebSocket messages)",
            f"# Total parsed: {len(fs_calls)} Firestore RPC operations",
            "###############################################################################",
            "",
            "# Firestore WS message format:",
            "#   {a: action, t: streamToken, d: {target: N, ...}}",
            "#   Action codes: 1=listen, 2=unlisten, 3=rpc, 4=snapshot, 5=health",
            "#",
            "",
            "# ── Listen targets (subscription queries) ──",
        ]
        listen_calls = [c for c in fs_calls if c.get("action") == "listen"]
        if listen_calls:
            for call in listen_calls[:20]:
                target = call.get("target_id", "?")
                token = call.get("stream_token", "")[:40]
                lines.append(f"#   Target {target} | token: {token}...")
            if len(listen_calls) > 20:
                lines.append(f"#   ... and {len(listen_calls) - 20} more listen calls")

        lines += [
            "",
            "# ── Full Firestore message log ──",
        ]
        for call in fs_calls[:30]:
            lines.append(
                f"# [{call['call_id']}] action={call['action']} "
                f"target={call.get('target_id', '?')} "
                f"token={str(call.get('stream_token', '') or '')[:30]}..."
            )
        if len(fs_calls) > 30:
            lines.append(f"# ... and {len(fs_calls) - 30} more calls")

    # ── websocat installation reminder ──────────────────────────────────────────
    lines += [
        "",
        "###############################################################################",
        "# INSTALL WEBSOCAT",
        "###############################################################################",
        "#",
        "# macOS:",
        "#   brew install websocat",
        "#",
        "# Linux:",
        "#   curl -sL https://github.com/.../websocat/releases  # download binary",
        "#   # Or use your package manager",
        "#",
        "# Python (less full-featured):",
        "#   pip install websocat",
        "#",
    ]

    return "\n".join(lines) + "\n"


def render_firestore_ws_python(ws_capture_path: str | Path) -> str:
    """Generate a Python Firebase Firestore WebSocket client.

    Parses captured Firestore WS frames and generates a Python script
    that can replay the listen queries using the Firebase REST API
    (as a fallback when WS replay isn't available).
    """
    import json
    from pathlib import Path

    data = json.loads(Path(ws_capture_path).read_text())
    fs_calls = data.get("firestore_calls", [])
    connections = data.get("connections", [])
    firestore_conns = [c for c in connections if c.get("is_firestore")]

    lines = [
        '"""',
        "Firebase Firestore WebSocket replay — generated by browserclaw.",
        f"Parsed {len(fs_calls)} Firestore RPC calls from {len(firestore_conns)} WS connection(s).",
        "",
        "NOTE: Firestore WS stream tokens expire. This script shows the parsed structure",
        "      of the listen queries — replay requires a fresh stream token.",
        '"""',
        "",
        "# Firestore WS message reference:",
        "#   a=1: listen (subscribe to a query target)",
        "#   a=2: unlisten (unsubscribe)",
        "#   a=3: rpc (direct RPC call)",
        "#   a=4: snapshot (response)",
        "#",
        "# Target format (from captured messages):",
        "#   {targetId: N, documents: {documents: ['projects/.../documents/...']}}",
        "#   OR",
        "#   {targetId: N, queries: [{structuredQuery: {...}}]}",
        "",
    ]

    if fs_calls:
        lines += [
            "",
            "# ── Parsed Firestore RPC calls ──",
            "",
        ]
        for call in fs_calls[:30]:
            payload = call.get("raw_payload", {})
            lines.append(f"# Call {call['call_id']}: action={call['action']}")
            lines.append(f"#   target_id={call.get('target_id')}")
            lines.append(f"#   payload: {json.dumps(payload, indent=2)[:300]}")
            lines.append("")

    return "\n".join(lines) + "\n"


def generate_ws_bundle(ws_capture_path: str | Path, output_dir: str | Path) -> dict[str, Path]:
    """Generate WebSocket replay bundle: websocat shell script + Python parser."""
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)

    replay_path = output / "ws_replay.sh"
    python_path = output / "ws_firestore_analysis.py"

    replay_path.write_text(render_ws_replay(ws_capture_path))
    python_path.write_text(render_firestore_ws_python(ws_capture_path))

    return {
        "replay": replay_path,
        "analysis": python_path,
    }

