from __future__ import annotations

import json
from pathlib import Path

from .models import EndpointCatalog


def _python_method_name(name: str) -> str:
    return name.replace("-", "_")


def render_python_client(catalog: EndpointCatalog, *, class_name: str = "BrowserClawClient") -> str:
    methods: list[str] = []
    for endpoint in catalog.endpoints:
        query_arg_names = [key.replace("-", "_") for key in endpoint.query_keys]
        body_arg_names = [key.replace("-", "_") for key in endpoint.request_body_keys]
        method_args = ["self", "*"]
        method_args.extend(f"{name}=None" for name in query_arg_names + body_arg_names)
        method_name = _python_method_name(endpoint.name)
        query_payload = ", ".join([f'"{key}": {key.replace("-", "_")}' for key in endpoint.query_keys]) or ""
        json_payload = ", ".join([f'"{key}": {key.replace("-", "_")}' for key in endpoint.request_body_keys]) or ""
        methods.append(
            f"""    def {method_name}({", ".join(method_args)}):\n"""
            f"""        \"\"\"{endpoint.description}\"\"\"\n"""
            f"""        params = {{{query_payload}}}\n"""
            f"""        params = {{key: value for key, value in params.items() if value is not None}}\n"""
            f"""        payload = {{{json_payload}}}\n"""
            f"""        payload = {{key: value for key, value in payload.items() if value is not None}}\n"""
            f"""        response = self.session.request(\n"""
            f"""            "{endpoint.method}",\n"""
            f"""            "{endpoint.url_template}",\n"""
            f"""            params=params or None,\n"""
            f"""            json=payload or None,\n"""
            f"""        )\n"""
            f"""        response.raise_for_status()\n"""
            f"""        return response.json() if response.content else None\n"""
        )

    return f'''"""Generated by browserclaw from {catalog.source_har}."""\n\nimport requests\n\n\nclass {class_name}:\n    def __init__(self, session: requests.Session | None = None):\n        self.session = session or requests.Session()\n\n{"\n\n".join(methods)}\n'''


def render_mcp_tools(catalog: EndpointCatalog) -> dict:
    tools = []
    for endpoint in catalog.endpoints:
        properties = {}
        required = []
        for key in endpoint.query_keys + endpoint.request_body_keys:
            safe_name = key.replace("-", "_")
            properties[safe_name] = {
                "type": "string",
                "description": f"Inferred parameter for {key}",
            }
        tools.append(
            {
                "name": endpoint.name,
                "description": endpoint.description or f"{endpoint.method} {endpoint.url_template}",
                "inputSchema": {
                    "type": "object",
                    "properties": properties,
                    "required": required,
                    "additionalProperties": False,
                },
                "annotations": {
                    "method": endpoint.method,
                    "urlTemplate": endpoint.url_template,
                },
            }
        )
    return {
        "schema_version": "2025-03-26",
        "site": catalog.site,
        "tools": tools,
    }


def generate_bundle(catalog: EndpointCatalog, output_dir: str | Path) -> dict[str, Path]:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    catalog_path = output / "catalog.json"
    client_path = output / "generated_client.py"
    mcp_path = output / "mcp_tools.json"
    catalog_path.write_text(json.dumps(catalog.to_dict(), indent=2) + "\n")
    client_path.write_text(render_python_client(catalog))
    mcp_path.write_text(json.dumps(render_mcp_tools(catalog), indent=2) + "\n")
    return {
        "catalog": catalog_path,
        "client": client_path,
        "mcp": mcp_path,
    }

